title: "cd ~"
theme: minima
markdown: kramdown
lang: en

# 새로 추가한 내용들
description: computer science study archive, etc
author: ""

email: peter584aa@knu.ac.kr

goatcounter: pedro1798

kramdown: 
 input: GFM
 hard_wrap: true

minima: 
  social_links:
    github: pedro1798
  skin: auto
  date_format: "%Y-%m-%d"


header_pages:
  - study.md
  - paper.md
  - project.md
  - books.md
  - writings.md

collections:
  study:
    output: true
    permalink: /study/:path/
  paper:
    output: true
  project:
    output: true

