title: "Home"
theme: minima
markdown: kramdown
lang: en

# 새로 추가한 내용들
description: 아아 테스트 
author: 
  name: pedro1798

email: peter584aa@knu.ac.kr

goatcounter: pedro1798

kramdown: 
 input: GFM
 hard_wrap: true

minima: 
  social_links:
    github: pedro1798
  skin: auto
  date_format: "%Y-%m-%d"


header_pages:
  - study.md
  - paper.md
  - project.md
  - writings.md
  - books.md

collections:
  study:
    output: true
    permalink: /study/:path/
  paper:
    output: true
  project:
    output: true
  writings:
    output: true

