title: ""
theme: minima
markdown: kramdown
lang: en

kramdown: 
 input: GFM
 hard_wrap: true

minima: 
  social_links:
    github: pedro1798

collections:
  study:
    output: true
  paper:
    output: true
  project:
    output: true
  writings:
    output: true
