title: "Home"
theme: minima
markdown: kramdown
lang: en

goatcounter: pedro1798.github.io

pageviews:
  provider: goatcounter

tagline: 아아 테스트 

kramdown: 
 input: GFM
 hard_wrap: true

minima: 
  social_links:
    github: pedro1798


header_pages:
  - study.md
  - paper.md
  - project.md
  - writings.md
  - books.md

collections:
  study:
    output: true
    permalink: /study/:path/
  paper:
    output: true
  project:
    output: true
  writings:
    output: true

